import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import CallToAction from '../components/CallToAction'

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>SocialFed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" media="print" onLoad="this.onload=null;this.removeAttribute('media');" href="https://rsms.me/inter/inter.css"></link>
      </Head>
      <Navbar />
      <main>
        <Hero />
        <CallToAction />
      </main>
    </React.Fragment >
  )
}
