import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <React.Fragment>
      <Navbar />
      <Head>
        <title>SocialFed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"></link>
      </Head>

      <main>
        <h1 className='text-4xl font-bold flex justify-center mt-12'>SocialFed</h1>
      </main>
    </React.Fragment >
  )
}
